version: '2.19.1'
services:
  nest-app:
    container_name: nest-app
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - '3000:3000'
    # networks:
    #   - common-network
  mysql-container:
    container_name: mysql-container
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - SESSION_SECRET
    ports:
      - '3306:3306'
    volumes:
      - /Users/zhoujin/mysql-data:/var/lib/mysql
    # networks:
    #   - common-network
  redis-container:
    container_name: redis-container
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - /Users/zhoujin/aaa:/data
    # networks:
    #   - common-network
# networks:
#   common-network:
#     driver: bridge
