version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management # 带管理界面的官方镜像
    ports:
      - "5672:5672" # AMQP 端口
      - "15672:15672" # Web 管理界面端口
    environment:
      RABBITMQ_DEFAULT_USER: admin # 默认用户名
      RABBITMQ_DEFAULT_PASS: admin123 # 默认密码
    volumes:
      - D:/software/docker/RabbitMQ:/var/lib/rabbitmq # 数据持久化
